  
name: "My CodeQL config1"

disable-default-queries: true

languages: java

queries:
  - name: Extended Security
    uses: security-extended
  - name: Security and Quality
    uses: security-and-quality
https://github.com/vishal-ceg/ecom-service/blob/dev1/.github/config.yml
